### ISSUE TITLE
All Day events not working properly

### ISSUE THREAD

**Issue by cpw7922** [PTST/O365Calendar-HomeAssistant#85]
My all day events are showing up as 8pm-8pm instead of All Day events. Non-All Day events show up just fine. Not sure if all_day or is_all_day is being looked at 

v0.115 Calendar Card
![image](https://user-images.githubusercontent.com/63802691/93526942-28ed9400-f906-11ea-8580-27aab2372771.png)

Custom Calendar Card
![image](https://user-images.githubusercontent.com/63802691/93526319-48d08800-f905-11ea-9d76-b969ccf20e1f.png)

```
message: Test
all_day: false
start_time: '2020-09-16 20:00:00'
end_time: '2020-09-17 20:00:00'
location:
  displayName: ''
  locationType: default
  uniqueIdType: unknown
  address: {}
  coordinates: {}
description: ''
offset_reached: false
data:
  - summary: Test
    description: ''
    location: ''
    categories: []
    sensitivity: Normal
    show_as: Free
    is_all_day: true
    attendees: []
    start: '2020-09-17T00:00:00+00:00'
    end: '2020-09-18T00:00:00+00:00'
```
