### ISSUE TITLE
How can I set a trigger when there is an agenda item today?

### ISSUE THREAD

**Issue by wolfhond** [PTST/O365Calendar-HomeAssistant#96]
How can I set a trigger when there is an agenda item today?
Or tomorrow?

Is this possible?

**Comment by magaxel** [comment]
I use the following to produce a Google Push notification when there is a calendar event:

 In /config/automations.yaml

```
- id: trash_push
  alias: Trash push
  trigger:
    platform: state
    entity_id:
    - calendar.trash
    to: 'on'
  action:
    service: notify.google_push
    data_template:
      message: Take out the trash
```

In /config/o365_calendars.yaml
```
- cal_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  entities:
  - device_id: trash
    name: 'Take out the trash'
    start_offset: 14
    track: true
    search: 'Take out the trash'
```
I use 'start_offset' to trigger the event before its scheduled in Outlook
